window_prefix: "\uf418 " # Use nerdtree branch icon as prefix
merge_strategy: rebase # Make workmux merge do rebase by default
agent: claude
worktree_naming: basename

panes:
  - command: Shell
    focus: true

status_icons:
  working: 'ðŸ¤–' # Agent is processing
  waiting: 'ðŸ’¬' # Agent needs input (auto-clears on focus)
  done: 'âœ…' # Agent finished (auto-clears on focus)
